### ISSUE TITLE
Road to 1.0

### ISSUE THREAD

**Issue by danielgtaylor** [apiaryio/fury.js#51]
This issue will track the progress toward a new major version release of Fury.js that works on all maintained versions of Node.js and is a lightweight, Refract-based core for an API SDK.
- [x] Refract release with protagonist 1.0.0 (#48)
- [x] Document all elements in refractproject/minim-api-description#6
- [x] Swagger adapter in apiaryio/fury-adapter-swagger#1
- [x] Remove legacy code & support newer Node.js versions (#25)
- [x] Rewrite user documentation for Fury + plugins
- [x] Browser support

**Comment by pksunkara** [comment]
Shouldn't this be 1.1.0? Since we are planning to release 1.0.0 after #48?

**Comment by danielgtaylor** [comment]
> Remove legacy code

@pksunkara I think the above requires a major version bump, so maybe 2.0 if #48 is going to be 1.0.

**Comment by pksunkara** [comment]
We have decided to release current as 0.9.0 and this final release as 1.0.0

**Comment by danielgtaylor** [comment]
We've now pushed up a non-legacy Fury release to unblock further development of Fury adapters. Everything in the list above should now work, but there are some open questions around browser support. Currently, it works with something like browserify/webpack, but we may want to provide minified browser-ready builds ourselves. I'll leave that for a future discussion.
